# Generated by Django 5.1.1 on 2024-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_map_description_alter_map_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='Item_Model',
            field=models.CharField(default='N/a', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='Serial_Number',
            field=models.CharField(default='N/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
