# Generated by Django 5.1.1 on 2024-10-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitemlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItemLog',
        ),
    ]
