# Generated by Django 5.1.1 on 2024-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventorylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='item_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
