# Generated by Django 5.1.1 on 2024-10-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventorylog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='equipment',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='station',
            name='map',
        ),
    ]
