# Generated by Django 5.1.1 on 2024-10-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_stationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
