# Generated by Django 5.1.1 on 2024-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_delete_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='station',
            name='y_coordinate',
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
