# Generated by Django 5.1.1 on 2024-10-14 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_station_x_coordinate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationlog',
            options={},
        ),
        migrations.AddField(
            model_name='stationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='station',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
