# Generated by Django 5.1.1 on 2024-10-14 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_stationlog_options_stationlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Station Logs'},
        ),
        migrations.RemoveField(
            model_name='stationlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.station'),
        ),
        migrations.AlterField(
            model_name='stationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
