# Generated by Django 5.1.1 on 2024-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_stationlog_options_remove_stationlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=800)),
                ('height', models.IntegerField(default=600)),
            ],
        ),
    ]
