# Generated by Django 5.1.1 on 2024-10-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField(default=0)),
                ('start_y', models.FloatField(default=0)),
                ('end_x', models.FloatField()),
                ('end_y', models.FloatField()),
                ('color', models.CharField(max_length=7)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.map')),
            ],
        ),
    ]
