# Generated by Django 5.1.1 on 2024-10-16 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='end_x',
        ),
        migrations.RemoveField(
            model_name='line',
            name='end_y',
        ),
        migrations.RemoveField(
            model_name='line',
            name='map',
        ),
        migrations.RemoveField(
            model_name='line',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='line',
            name='start_y',
        ),
        migrations.AddField(
            model_name='line',
            name='endX',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='endY',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='startX',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='startY',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
