# Generated by Django 5.1.1 on 2024-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_line_end_x_remove_line_end_y_remove_line_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='endX',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='endY',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='startX',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='startY',
            field=models.IntegerField(default=0),
        ),
    ]
